### ISSUE TITLE
titleを工夫する

### ISSUE THREAD

**Issue by hkurokawa** [AndroidDagashi/androiddagashi.github.io#54]
直接のきっかけ

<blockquote class="twitter-tweet" data-lang="en"><p lang="ja" dir="ltr"><a href="https://twitter.com/hydrakecat?ref_src=twsrc%5Etfw">@hydrakecat</a>  Hey! このSEOしようという気持ちがかけらもない &lt;title/&gt; はちょっとないんじゃあないですか！もっとがんばりましょうよ！ <a href="https://t.co/4ZtCIFe8PA">https://t.co/4ZtCIFe8PA</a></p>&mdash; FUJI Goro (@__gfx__) <a href="https://twitter.com/__gfx__/status/1056710392917876736?ref_src=twsrc%5Etfw">October 29, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

いくつか案を出して検討してみたい。

**Comment by hkurokawa** [comment]
参考：JSer.info はこんな感じ
`2018-10-21のJS: Chrome 70、Angular 7、LoopBack 4 GA`

**Comment by hkurokawa** [comment]
目的：SEO（他にももうちょっと一覧性を上げたいとかあるけれど、とりあえずは検索に引っかかってクリックしてもらうのが目的）

【A案】
概要と同じ内容をタイトルにも含める。ただし文字数が長くなるのが悩ましい。

【B案】
概要をさらに切り詰めたタイトルを考える。そもそもそんなに毎週ニュースがあるわけでもないので、ちょっと大変そう……。

【C案】
いまのものに AndroidDagashi というサイト名だけくっつける。一覧で見たときに鬱陶しい……。

**Comment by yshrsmz** [comment]
ogじゃない`description`も追加してみたらいいかも…？
文字数も結構書けそうだし
https://webtan.impress.co.jp/e/2018/02/19/28312

**Comment by hkurokawa** [comment]
おお :clap:  とりあえず実験的に次回のマイルストーンタイトルは概要を短くしたものを付けてみようと思うのですが、どうでしょうかー。急にばたばたとすみません :bowing_man:

**Comment by hkurokawa** [comment]
お、なるほど。後者の機械的にやる方がお試しとしてはいいですかね。お手を煩わせてしまってすみません :bowing_man:

**Comment by yshrsmz** [comment]
一旦クローズしときます
何かあったらまた
